[build]
  publish = "exampleSite/public"
  command = "cd exampleSite && hugo"

[context.production]
  [context.production.environment]
    HUGO_VERSION = "0.38"
    HUGO_BASEURL = "https://dream-plus.netlify.com/"