baseURL = "https://www.examplesite.com"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Author's Blog"
theme = "hugo-dream-plus"

copyright = "Copyright (C) 2018, UtkarshVerma; All Rights Reserved."
googleAnalytics = ""

disqusShortname = ""

enableRobotsTXT = true

hasCJKLanguage = false

#Enable Hugo Emoji Conversion
enableEmoji=true

[params]
  author = "Author"
  description = ""
  avatar = "/img/defaultAvatar.jpg"
  motto = "Author motto."
  #Enable table of contents for posts.
  enableToc = true
  #Enable Sharing option for posts.
  enableShareCard = true
 
  #Use your external CSS/JS files with this theme by placing the location of the file within the list. For example: "js/twemoji.js" 
  customCSS = [""]
  customJS  = [""]
  favicon = "/img/defaultFav.ico"
  
#Background Settings
  enableColorBG= true

  bgBlur = 0.5
  bgImage = "/img/bg1.jpeg"

# Heading for Error Page
  error404 = "Error 404: Page Not Found"

# Set the heading for the about page!
  aboutHeader = ""

  #List of background images.
  bgList = ["/img/bg1.jpeg"]
  
# Post-displaying Settings  
  enablePost = true
  enableTags = true
  enableCategories = true
  postsPerPage = 4

#Enable Twitter Emoji
  twitterEmoji=true

#Link of your blog
  BlogLink = ""


#Social Links. Only insert the username.
  email = ""
  github = "UtkarshVerma"
  linkedin = ""
  codepen = ""
  stackoverflow = ""
  medium = ""
  reddit = ""
  twitter = "" 
  siteStartYear = 2018
 
