baseURL = "https://example.com"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Author's Site"
theme = "dream-plus"

copyright = ""
googleAnalytics = ""

disqusShortname = ""

enableRobotsTXT = true

hasCJKLanguage = false

#Enable Hugo Emoji Conversion
enableEmoji=true

[params]
  author = "Author"
  description = "Site description"
  #avatar = ""
  motto = "Author's motto or short description."
  enableToc = true
  enableShareCard = true
 
  #Use your external CSS/JS files with this theme by placing the location of the file within the list. For example: "js/twemoji.js" 
  customCSS = [""]
  customJS  = [""]
  favicon = "/img/defaultFav.ico"
    
  #Shorte.st Settings
  enableShortest = false  
  
#Background Settings
  enableColorBG= false
  bgBlur = 0.5
  bgImage = "/img/bg1.jpeg"
  bgList = ["/img/bg1.jpeg"]
  
# Post-displaying Settings
  enableTags = true
  enableCategories = true

# Cards or posts shown per page
  itemsPerPage = 4

# Set whether you're hosting "cards" or "post"
  contentType = "post"

# Enable/disable post/card  dimming effect
  enableDimmer = true

# Heading for 404 Page
  error404 = "Error 404: Page Not Found"

  #Enable Twitter Emoji
  twitterEmoji=true

#Heading for the About page
  aboutHeader = "About the Author"

#Link to your blog
  BlogLink = ""

#Social Links
  email = "utkarshverma@protonmail.com"
  github = "UtkarshVerma"
  linkedin = ""
  codepen = ""
  stackoverflow = "9271608/utkarsh-verma"
  medium = "UtkarshVerma_"
  twitter = "UtkarshVerma_" 
  siteStartYear = 2018
 
